### ISSUE TITLE
personal_* missing

### ISSUE THREAD

**Issue by jacogr** [ethcore/ethereum-rpc-json#1]
The `personal_listAccounts` RPC call is missing. Parity maps it here 

https://github.com/ethcore/parity/blob/master/rpc/src/v1/traits/personal.rs#L39
https://github.com/ethcore/parity/blob/master/rpc/src/v1/impls/personal.rs#L50

Also `personal_signerEnabled` as per comment below.

**Comment by tomusdrw** [comment]
~~\+ personal_signerEnabled~~

**Comment by goldylucks** [comment]
@jacogr this was closed via #6 ?

**Comment by jacogr** [comment]
Closed via #6
