### ISSUE TITLE
some ethcore_* calls missing

### ISSUE THREAD

**Issue by jacogr** [ethcore/ethereum-rpc-json#2]
Comparison with https://github.com/ethcore/parity-dapps-status/blob/master/client/provider/web3-ethcore-provider.js#L5 missing

ethcore_defaultExtraData
ethcore_devLogs
ethcore_devLogsLevels

**Comment by tomusdrw** [comment]
+ personal_signerEnabled

**Comment by jacogr** [comment]
Closed via #6
